import { useMemo } from "react";

import type {
  AgentSummary,
  BrainGraph,
  BrainNode,
  BrainNodeKind,
  BriefingRow,
  Goal,
  GoalsSummary,
  HeartbeatResponse,
  HeartbeatSeries,
  InboxItem,
  InboxSummary,
} from "@blankcollar/shared";

import { ChannelMark, I, Sigil } from "../icons";
import { api } from "../lib/api";
import { progressPercent, relativeTime } from "../lib/format";
import { useFetch } from "../lib/useFetch";

/**
 * Editorial dashboard — Phase 4 front door.
 *
 * Replaces the design's fixture data with live API calls. Three pillars:
 *   1. Today's briefing prose at the top (auto-generated by /api/briefing/today)
 *   2. Real "wants your attention" inbox + active goals + heartbeat
 *   3. Brain mini tied to /api/brain/graph
 *
 * If a panel can't load, it degrades gracefully — never blocks the rest
 * of the dashboard.
 */

const HEARTBEAT_SHOWN: { kpi: string; positive: boolean }[] = [
  { kpi: "captures",       positive: true  },
  { kpi: "runs_completed", positive: true  },
  { kpi: "runs_failed",    positive: false },
  { kpi: "goals_active",   positive: true  },
];

type Props = {
  onOpenGoal: (id: string) => void;
  onOpenBrain: () => void;
};

export function Dashboard({ onOpenGoal, onOpenBrain }: Props) {
  const briefingQ = useFetch<BriefingRow>(() => api.getBriefingToday(), []);
  const heartbeatQ = useFetch<HeartbeatResponse>(() => api.getHeartbeat({ days: 14 }), []);
  const summaryQ = useFetch<GoalsSummary>(() => api.getGoalsSummary(), []);
  const inboxQ = useFetch<InboxItem[]>(() => api.listInbox({ limit: 4 }), []);
  const inboxSummaryQ = useFetch<InboxSummary>(() => api.inboxSummary(), []);
  const liveGoalsQ = useFetch<Goal[]>(() => api.listGoals({ status: "active", limit: 8 }), []);
  const doneGoalsQ = useFetch<Goal[]>(() => api.listGoals({ status: "achieved", limit: 4 }), []);
  const agentsQ = useFetch<AgentSummary[]>(() => api.listAgents({ isActive: true }), []);
  const brainQ = useFetch<BrainGraph>(() => api.getBrainGraph({ limit: 40 }), []);

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });

  const subline = useMemo(() => {
    const u = inboxSummaryQ.data?.urgent ?? 0;
    const t = inboxSummaryQ.data?.total ?? 0;
    if (u === 0 && t === 0) return "Nothing wants you right now. Everything's moving on its own.";
    if (u === 0) return `${t} item${t === 1 ? "" : "s"} in your inbox; nothing urgent.`;
    if (u === t) return `${u} thing${u === 1 ? "" : "s"} want${u === 1 ? "s" : ""} your attention today.`;
    return `${u} urgent of ${t} in your inbox today.`;
  }, [inboxSummaryQ.data]);

  return (
    <div className="page">
      <div className="page-head">
        <div className="meta">
          <div className="editorial-eyebrow">
            Today's briefing · {today}
          </div>
          <div className="titlerow">
            <div className="h1">Good {timeOfDay()}.</div>
          </div>
          <div className="small" style={{ maxWidth: 620, marginTop: 4 }}>
            {subline}
          </div>
        </div>
        <div className="stack-h" style={{ alignItems: "center" }}>
          <span className="tiny mono">{today}</span>
          <span className="vrule" style={{ height: 28 }} />
          <button
            className="btn btn-sm"
            onClick={() => {
              void api.generateBriefing({ kind: "daily" }).then(() => briefingQ.refetch());
            }}
            disabled={briefingQ.loading}
            title="Re-generate today's briefing"
          >
            <I name="play" size={11} /> Refresh briefing
          </button>
        </div>
      </div>

      <BriefingCard q={briefingQ} />

      <StatStrip summary={summaryQ.data} heartbeat={heartbeatQ.data} />

      <div className="twocol">
        <div className="left">
          <section className="section">
            <div className="section-head">
              <div className="stack-h">
                <span className="title">Wants your attention</span>
                <span className="pill">
                  {inboxSummaryQ.data?.total ?? inboxQ.data?.length ?? "—"} item
                  {(inboxSummaryQ.data?.total ?? inboxQ.data?.length ?? 0) === 1 ? "" : "s"}
                </span>
              </div>
              <div className="stack-h">
                <span className="tiny mono">
                  {inboxQ.loading
                    ? "Loading…"
                    : inboxQ.error
                    ? "Couldn't load"
                    : inboxQ.data && inboxQ.data.length > 0
                    ? `Updated ${relativeTime(inboxQ.data[0]!.created_at)}`
                    : "All clear"}
                </span>
              </div>
            </div>
            <InboxRail
              items={inboxQ.data ?? []}
              loading={inboxQ.loading}
              error={inboxQ.error}
              onOpenGoal={onOpenGoal}
            />
          </section>

          <section className="section">
            <div className="section-head">
              <div className="stack-h">
                <span className="title">Active goals</span>
                <span className="pill">
                  {summaryQ.data?.by_status.active ?? liveGoalsQ.data?.length ?? "—"}
                </span>
              </div>
              <div className="stack-h">
                <button className="btn btn-ghost btn-sm" disabled>
                  <I name="filter" size={12} /> Filter
                </button>
                <button className="btn btn-ghost btn-sm" disabled>
                  <I name="sort" size={12} /> Sort
                </button>
              </div>
            </div>
            <GoalList
              goals={liveGoalsQ.data ?? []}
              loading={liveGoalsQ.loading}
              error={liveGoalsQ.error}
              onOpenGoal={onOpenGoal}
              emptyHint="No active goals. Capture one to get going."
            />
          </section>

          <section className="section">
            <div className="section-head">
              <div className="stack-h">
                <span className="title">This week's pulse</span>
                <span className="tiny mono">14d window</span>
              </div>
            </div>
            <PulseStrip heartbeat={heartbeatQ.data} summary={summaryQ.data} />
          </section>

          <section className="section">
            <div className="section-head">
              <div className="stack-h">
                <span className="title">Recently closed</span>
                <span className="pill">{doneGoalsQ.data?.length ?? "—"}</span>
              </div>
            </div>
            <GoalList
              goals={doneGoalsQ.data ?? []}
              loading={doneGoalsQ.loading}
              error={doneGoalsQ.error}
              onOpenGoal={onOpenGoal}
              emptyHint="Nothing closed yet — wins land here as they ship."
            />
          </section>
        </div>

        <div className="right">
          <div className="rail-section">
            <div className="section-head" style={{ marginBottom: 12 }}>
              <span className="title">Heartbeat</span>
              <span className="tiny mono">{heartbeatQ.data?.period_days ?? 14}d</span>
            </div>
            <HeartbeatRail q={heartbeatQ.data} loading={heartbeatQ.loading} error={heartbeatQ.error} />
          </div>

          <div className="rail-section">
            <div className="section-head" style={{ marginBottom: 12 }}>
              <span className="title">Live now</span>
              <span className="live-tag">
                <span className="dot" />
                {agentsQ.data?.length ?? 0}
              </span>
            </div>
            <AgentRail agents={agentsQ.data ?? []} loading={agentsQ.loading} error={agentsQ.error} />
          </div>

          <div className="rail-section">
            <div className="section-head" style={{ marginBottom: 12 }}>
              <span className="title">Across your channels</span>
              <span className="tiny mono" style={{ color: "var(--muted)" }}>v2</span>
            </div>
            <div className="stack-v" style={{ gap: 10 }}>
              {[
                { ch: "telegram", label: "Telegram", note: "Bot live · v1 round-trip wired", dot: "live" },
                { ch: "slack", label: "Slack", note: "Coming soon", dot: "idle" },
                { ch: "whatsapp", label: "WhatsApp", note: "Coming soon", dot: "idle" },
                { ch: "email", label: "Email", note: "Coming soon", dot: "idle" },
              ].map((c) => (
                <div key={c.ch} style={{ display: "flex", alignItems: "center", gap: 10 }}>
                  <ChannelMark ch={c.ch} size={20} />
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 12.5 }}>{c.label}</div>
                    <div className="tiny">{c.note}</div>
                  </div>
                  <span className={`dot ${c.dot}`} />
                </div>
              ))}
            </div>
          </div>

          <div className="rail-section">
            <div className="section-head" style={{ marginBottom: 12 }}>
              <span className="title">Company brain</span>
              <button className="btn btn-ghost btn-sm" onClick={onOpenBrain}>
                Open
                <I name="arrow" size={12} />
              </button>
            </div>
            <div
              style={{
                height: 140,
                position: "relative",
                overflow: "hidden",
                border: "1px solid var(--line)",
                borderRadius: 4,
                background: "var(--bg)",
              }}
            >
              <BrainMini graph={brainQ.data} />
            </div>
            <div className="tiny" style={{ marginTop: 10 }}>
              <span className="num">{brainQ.data?.nodes.length ?? "—"}</span> nodes · last refreshed{" "}
              {brainQ.data ? relativeTime(brainQ.data.generated_at) : "—"}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── briefing card ─────────────────────────────────────────────────────

function BriefingCard({
  q,
}: {
  q: { data: BriefingRow | null; error: Error | null; loading: boolean };
}) {
  if (q.loading && !q.data) {
    return (
      <div
        style={{
          padding: "20px 22px",
          border: "1px solid var(--line)",
          borderLeft: "2px solid var(--ink-2)",
          borderRadius: "var(--radius-lg)",
          background: "var(--bg-1)",
          marginBottom: 16,
          color: "var(--muted)",
        }}
      >
        <div className="eyebrow" style={{ marginBottom: 6 }}>
          The newsroom
        </div>
        <div className="small">Drafting today's briefing…</div>
      </div>
    );
  }
  if (q.error) {
    return (
      <div
        style={{
          padding: "20px 22px",
          border: "1px solid var(--line)",
          borderLeft: "2px solid var(--neg)",
          borderRadius: "var(--radius-lg)",
          background: "var(--bg-1)",
          marginBottom: 16,
        }}
      >
        <div className="eyebrow" style={{ marginBottom: 6, color: "var(--neg)" }}>
          Briefing unavailable
        </div>
        <div className="small">{q.error.message}</div>
      </div>
    );
  }
  if (!q.data) return null;

  const narrated = (q.data.sources.narrated as boolean | undefined) ?? false;
  return (
    <div
      style={{
        padding: "22px 24px",
        border: "1px solid var(--line)",
        borderLeft: "2px solid var(--ink-2)",
        borderRadius: "var(--radius-lg)",
        background: "var(--bg-1)",
        marginBottom: 16,
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "baseline",
          justifyContent: "space-between",
          marginBottom: 10,
        }}
      >
        <div className="eyebrow">Today's briefing</div>
        <span className="tiny mono" style={{ color: "var(--muted)" }}>
          {narrated ? "Hermes-narrated" : "templated"} · {relativeTime(q.data.generated_at)}
        </span>
      </div>
      <Markdown text={q.data.summary_md} />
    </div>
  );
}

/** Lightweight markdown — handles `## headings`, `- bullets`, `**bold**`, paragraphs. */
function Markdown({ text }: { text: string }) {
  const lines = text.split("\n");
  const blocks: React.ReactNode[] = [];
  let para: string[] = [];
  let bullets: string[] = [];

  const flushPara = () => {
    if (para.length === 0) return;
    blocks.push(
      <p
        key={`p-${blocks.length}`}
        className="serif"
        style={{ fontSize: 16, lineHeight: 1.55, color: "var(--ink)", margin: "0 0 10px 0" }}
      >
        {renderInline(para.join(" "))}
      </p>,
    );
    para = [];
  };
  const flushBullets = () => {
    if (bullets.length === 0) return;
    blocks.push(
      <ul
        key={`ul-${blocks.length}`}
        style={{
          margin: "0 0 12px 0",
          paddingLeft: 18,
          fontSize: 13.5,
          lineHeight: 1.55,
          color: "var(--ink-2)",
        }}
      >
        {bullets.map((b, i) => (
          <li key={i}>{renderInline(b)}</li>
        ))}
      </ul>,
    );
    bullets = [];
  };

  for (const raw of lines) {
    const line = raw.trim();
    if (line.length === 0) {
      flushPara();
      flushBullets();
      continue;
    }
    if (line.startsWith("## ")) {
      flushPara();
      flushBullets();
      blocks.push(
        <h3
          key={`h-${blocks.length}`}
          className="eyebrow"
          style={{ marginTop: 14, marginBottom: 6 }}
        >
          {line.slice(3).trim()}
        </h3>,
      );
      continue;
    }
    if (line.startsWith("# ")) {
      flushPara();
      flushBullets();
      blocks.push(
        <h2
          key={`h-${blocks.length}`}
          className="serif"
          style={{
            fontSize: 22,
            fontWeight: 500,
            margin: "10px 0 8px 0",
            letterSpacing: "-0.01em",
          }}
        >
          {line.slice(2).trim()}
        </h2>,
      );
      continue;
    }
    if (line.startsWith("- ") || line.startsWith("* ")) {
      flushPara();
      bullets.push(line.slice(2).trim());
      continue;
    }
    flushBullets();
    para.push(line);
  }
  flushPara();
  flushBullets();

  return <div>{blocks}</div>;
}

function renderInline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (/^\*\*[^*]+\*\*$/.test(part)) {
      return (
        <strong key={i} style={{ fontWeight: 500, color: "var(--ink)" }}>
          {part.slice(2, -2)}
        </strong>
      );
    }
    return <span key={i}>{part}</span>;
  });
}

// ─── stat strip ────────────────────────────────────────────────────────

function StatStrip({
  summary,
  heartbeat,
}: {
  summary: GoalsSummary | null;
  heartbeat: HeartbeatResponse | null;
}) {
  const captures = seriesValues(heartbeat, "captures");
  const runs = seriesValues(heartbeat, "runs_completed");
  const failed = seriesValues(heartbeat, "runs_failed");

  const stats: { label: string; value: string; delta: string; deltaPos: boolean }[] = [
    {
      label: "Active goals",
      value: summary ? String(summary.by_status.active) : "—",
      delta: summary ? `${summary.total} total` : "—",
      deltaPos: true,
    },
    {
      label: "Decisions waiting",
      value: summary ? String(summary.by_kind.decision) : "—",
      delta: summary && summary.stalled_count > 0 ? `${summary.stalled_count} stalled` : "all on pace",
      deltaPos: !summary || summary.stalled_count === 0,
    },
    {
      label: "Runs (14d)",
      value: String(sum(runs)),
      delta: failed && sum(failed) > 0 ? `${sum(failed)} failed` : "no failures",
      deltaPos: !failed || sum(failed) === 0,
    },
    {
      label: "Captures (14d)",
      value: String(sum(captures)),
      delta: trend(captures),
      deltaPos: trendPositive(captures),
    },
  ];

  return (
    <div className="stats">
      {stats.map((s) => (
        <div key={s.label} className="stat">
          <div className="label">{s.label}</div>
          <div className="v num">{s.value}</div>
          <div className={`delta ${s.deltaPos ? "pos" : "neg"}`}>
            {s.deltaPos ? "↑" : "↓"} {s.delta}
          </div>
        </div>
      ))}
    </div>
  );
}

function seriesValues(h: HeartbeatResponse | null, kpi: string): number[] {
  return (h?.series.find((s) => s.kpi === kpi)?.points ?? []).map((p) => p.value);
}
function sum(xs: number[]): number {
  return xs.reduce((a, b) => a + b, 0);
}
function trend(xs: number[]): string {
  if (xs.length < 4) return "—";
  const half = Math.floor(xs.length / 2);
  const a = sum(xs.slice(0, half));
  const b = sum(xs.slice(half));
  if (a === 0 && b === 0) return "quiet";
  const delta = b - a;
  if (delta === 0) return "steady";
  return `${delta > 0 ? "+" : ""}${delta}`;
}
function trendPositive(xs: number[]): boolean {
  if (xs.length < 4) return true;
  const half = Math.floor(xs.length / 2);
  return sum(xs.slice(half)) >= sum(xs.slice(0, half));
}

// ─── pulse strip (replaces fake "this week's outcomes") ──────────────

function PulseStrip({
  heartbeat,
  summary,
}: {
  heartbeat: HeartbeatResponse | null;
  summary: GoalsSummary | null;
}) {
  const captures = seriesValues(heartbeat, "captures");
  const runs = seriesValues(heartbeat, "runs_completed");
  const failed = seriesValues(heartbeat, "runs_failed");
  const last7 = (xs: number[]) => xs.slice(-7);

  const tiles: { v: string; l: string; sub: string }[] = [
    {
      v: String(sum(last7(captures))),
      l: "Captures · 7d",
      sub: "What you handed the system",
    },
    {
      v: String(sum(last7(runs))),
      l: "Runs completed · 7d",
      sub: sum(last7(failed)) > 0 ? `${sum(last7(failed))} failed runs` : "Clean week so far",
    },
    {
      v: summary ? String(summary.by_kind.routine + summary.by_kind.standing) : "—",
      l: "On autopilot",
      sub: "Routines + standing goals",
    },
  ];

  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(3, 1fr)",
        gap: 0,
        border: "1px solid var(--line)",
        borderRadius: 6,
        overflow: "hidden",
      }}
    >
      {tiles.map((c, i) => (
        <div
          key={i}
          style={{
            padding: 18,
            borderRight: i < 2 ? "1px solid var(--line)" : 0,
            background: "var(--bg-1)",
          }}
        >
          <div className="eyebrow" style={{ marginBottom: 8 }}>{c.l}</div>
          <div
            className="num"
            style={{ fontSize: 26, fontWeight: 500, letterSpacing: "-0.02em" }}
          >
            {c.v}
          </div>
          <div className="tiny" style={{ marginTop: 4 }}>{c.sub}</div>
        </div>
      ))}
    </div>
  );
}

// ─── inbox rail ────────────────────────────────────────────────────────

function InboxRail({
  items,
  loading,
  error,
  onOpenGoal,
}: {
  items: InboxItem[];
  loading: boolean;
  error: Error | null;
  onOpenGoal: (id: string) => void;
}) {
  if (loading && items.length === 0) {
    return <Hint>Reading the inbox…</Hint>;
  }
  if (error) {
    return <HintError msg={error.message} />;
  }
  if (items.length === 0) {
    return <Hint>Nothing pending. Your day is clear.</Hint>;
  }
  return (
    <div className="card" style={{ padding: 0, overflow: "hidden" }}>
      {items.map((it, i) => (
        <div
          key={`${it.goal_id}-${i}`}
          onClick={() => onOpenGoal(it.goal_id)}
          style={{
            display: "grid",
            gridTemplateColumns: "auto 1fr auto",
            gap: 16,
            padding: "16px 18px",
            alignItems: "center",
            borderBottom: i < items.length - 1 ? "1px solid var(--line)" : 0,
            cursor: "pointer",
          }}
        >
          <div className="sigil" style={{ width: 36, height: 36 }}>
            <Sigil seed={it.goal_id} size={34} />
          </div>
          <div>
            <div style={{ fontSize: 13, fontWeight: 500 }}>
              {it.title}{" "}
              <span className="mono" style={{ color: "var(--muted)", fontSize: 11 }}>
                · {labelForKind(it.item_kind)}
              </span>
            </div>
            <div className="small" style={{ marginTop: 4 }}>
              {it.urgency === "urgent" ? "Urgent · " : ""}
              created {relativeTime(it.created_at)}
            </div>
          </div>
          <div className="stack-h">
            <button
              className="btn btn-sm"
              onClick={(e) => {
                e.stopPropagation();
                onOpenGoal(it.goal_id);
              }}
            >
              Review
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}

function labelForKind(k: InboxItem["item_kind"]): string {
  switch (k) {
    case "approval":       return "Approval";
    case "decision":       return "Decision";
    case "blocked":        return "Blocked";
    case "routine_output": return "Routine output";
    case "draft":          return "Draft";
  }
}

// ─── goal list ─────────────────────────────────────────────────────────

function GoalList({
  goals,
  loading,
  error,
  onOpenGoal,
  emptyHint,
}: {
  goals: Goal[];
  loading: boolean;
  error: Error | null;
  onOpenGoal: (id: string) => void;
  emptyHint: string;
}) {
  if (loading && goals.length === 0) return <Hint>Loading goals…</Hint>;
  if (error) return <HintError msg={error.message} />;
  if (goals.length === 0) return <Hint>{emptyHint}</Hint>;
  return (
    <div className="goal-list">
      {goals.map((g) => (
        <GoalRow key={g.id} g={g} onOpenGoal={onOpenGoal} />
      ))}
    </div>
  );
}

function GoalRow({ g, onOpenGoal }: { g: Goal; onOpenGoal: (id: string) => void }) {
  const pct = progressPercent(g);
  const dueLabel =
    g.due_at !== null
      ? new Date(g.due_at).toLocaleDateString("en-US", { month: "short", day: "numeric" })
      : g.kind === "routine" && g.cron_expr
      ? g.cron_expr
      : "no date";
  const statusColor =
    g.status === "active"
      ? "pos"
      : g.status === "paused"
      ? "warn"
      : g.status === "achieved"
      ? "info"
      : "idle";
  const sub =
    g.description?.split("\n")[0]?.slice(0, 90) ??
    `${g.kind} · ${g.status}`;
  return (
    <div className="goal-row" onClick={() => onOpenGoal(g.id)}>
      <div className="gn">{g.id.slice(0, 6)}</div>
      <div>
        <div className="gtitle">{g.title}</div>
        <div className="gsub">{sub}</div>
      </div>
      <div className="gprog">
        <div className="progressbar">
          <i style={{ width: `${pct}%` }} />
        </div>
        <span style={{ width: 28, textAlign: "right" }}>{pct}%</span>
      </div>
      <div className="gowner">
        <div className="sigil" style={{ width: 22, height: 22 }}>
          <Sigil seed={g.owner_id ?? g.id} size={20} />
        </div>
        <span style={{ fontSize: 12 }}>{g.kind}</span>
      </div>
      <div className="gdue">
        <span className={`dot ${statusColor}`} style={{ marginRight: 6 }} />
        {dueLabel}
      </div>
      <div className="gmore">
        <I name="chev" size={14} />
      </div>
    </div>
  );
}

// ─── heartbeat rail ────────────────────────────────────────────────────

function HeartbeatRail({
  q,
  loading,
  error,
}: {
  q: HeartbeatResponse | null;
  loading: boolean;
  error: Error | null;
}) {
  if (loading && !q) return <Hint>Reading pulse…</Hint>;
  if (error) return <HintError msg={error.message} />;
  if (!q) return null;

  return (
    <>
      {HEARTBEAT_SHOWN.map((s) => {
        const series = q.series.find((x) => x.kpi === s.kpi);
        if (!series) return null;
        const total = sum(series.points.map((p) => p.value));
        return (
          <div key={s.kpi} className="hb-row">
            <div>
              <div className="hbn">{series.label}</div>
              <div className="hbsub">
                {total} {series.unit} ·{" "}
                <span style={{ color: trendColor(series, s.positive) }}>{trend(series.points.map((p) => p.value))}</span>
              </div>
            </div>
            <Spark data={series.points.map((p) => p.value)} positive={s.positive} />
          </div>
        );
      })}
    </>
  );
}

function trendColor(s: HeartbeatSeries, kpiPositive: boolean): string {
  const xs = s.points.map((p) => p.value);
  const up = trendPositive(xs);
  // For positive KPIs (like captures), up means good. For runs_failed, up is bad.
  const isGood = kpiPositive ? up : !up;
  return isGood ? "var(--pos)" : "var(--warn)";
}

function Spark({ data, positive }: { data: number[]; positive: boolean }) {
  const max = Math.max(1, ...data);
  return (
    <div className="spark">
      {data.map((v, i) => (
        <i
          key={i}
          style={{
            height: `${Math.max(6, (v / max) * 100)}%`,
            background: positive ? "var(--ink-2)" : "var(--warn)",
            opacity: 0.4 + (i / Math.max(1, data.length)) * 0.6,
          }}
        />
      ))}
    </div>
  );
}

// ─── agent rail ────────────────────────────────────────────────────────

function AgentRail({
  agents,
  loading,
  error,
}: {
  agents: AgentSummary[];
  loading: boolean;
  error: Error | null;
}) {
  if (loading && agents.length === 0) return <Hint>Reading roster…</Hint>;
  if (error) return <HintError msg={error.message} />;
  if (agents.length === 0) return <Hint>No agents yet. Onboarding adds them.</Hint>;
  return (
    <>
      {agents.slice(0, 5).map((a) => (
        <div key={a.id} className="agent-item">
          <div className="sigil">
            <Sigil seed={a.id} size={30} />
          </div>
          <div>
            <div className="name">
              {a.name}
              <span className="role" style={{ marginLeft: 6 }}>{a.kind}</span>
            </div>
            <div className="activity">
              {a.is_active ? "live · ready" : "idle"}
            </div>
          </div>
          <span className={`dot ${a.is_active ? "live" : "idle"}`} />
        </div>
      ))}
    </>
  );
}

// ─── brain mini ────────────────────────────────────────────────────────

const BRAIN_RING: Record<BrainNodeKind, number> = {
  person: 12,
  agent: 22,
  goal: 32,
  capture: 40,
  tool: 46,
};

function BrainMini({ graph }: { graph: BrainGraph | null }) {
  const positions = useMemo(() => {
    if (!graph) return new Map<string, { x: number; y: number }>();
    const groups = new Map<BrainNodeKind, BrainNode[]>();
    for (const n of graph.nodes) {
      const arr = groups.get(n.kind) ?? [];
      arr.push(n);
      groups.set(n.kind, arr);
    }
    const out = new Map<string, { x: number; y: number }>();
    for (const [kind, items] of groups) {
      const r = BRAIN_RING[kind];
      items.forEach((n, i) => {
        const angle = (i / Math.max(1, items.length)) * Math.PI * 2;
        out.set(n.id, { x: 50 + Math.cos(angle) * r, y: 30 + Math.sin(angle) * r * 0.55 });
      });
    }
    return out;
  }, [graph]);

  if (!graph) return null;

  return (
    <svg viewBox="0 0 100 60" preserveAspectRatio="none" width="100%" height="100%">
      {graph.edges.slice(0, 40).map((e, i) => {
        const a = positions.get(e.from);
        const b = positions.get(e.to);
        if (!a || !b) return null;
        return (
          <line
            key={i}
            x1={a.x}
            y1={a.y}
            x2={b.x}
            y2={b.y}
            stroke="var(--line-2)"
            strokeWidth="0.3"
          />
        );
      })}
      {graph.nodes.slice(0, 50).map((n) => {
        const p = positions.get(n.id);
        if (!p) return null;
        return (
          <circle
            key={n.id}
            cx={p.x}
            cy={p.y}
            r={n.kind === "person" ? 1.4 : n.kind === "agent" ? 1.2 : n.kind === "goal" ? 1.0 : 0.7}
            fill={
              n.kind === "person"
                ? "var(--ink)"
                : n.kind === "agent"
                ? "var(--ink-2)"
                : n.kind === "goal"
                ? "var(--bg)"
                : "var(--muted)"
            }
            stroke={n.kind === "goal" ? "var(--ink)" : "none"}
            strokeWidth="0.4"
          />
        );
      })}
    </svg>
  );
}

// ─── helpers ───────────────────────────────────────────────────────────

function timeOfDay(): string {
  const h = new Date().getHours();
  if (h < 5) return "evening";
  if (h < 12) return "morning";
  if (h < 17) return "afternoon";
  return "evening";
}

function Hint({ children }: { children: React.ReactNode }) {
  return <div className="empty-hint">{children}</div>;
}
function HintError({ msg }: { msg: string }) {
  return (
    <div className="empty-hint" style={{ color: "var(--neg)" }}>
      Couldn't load · {msg}
    </div>
  );
}
